#!/bin/bash
#Requirements: mailutils must be installed STMP must be configured to send outgoing mail.  curl must also be installed.
#You will need to set your email address below
#I have some Newegg GTX 1080 and 1070 urls below.  You can add/remove as needed.  Only Newegg URLs will work at this time.
#Default is to check every 10 seconds until a match is found.  Then it will stop alerting for 5 min once an email has been set.

MYEMAIL=setyourmailaddresshere
URL=(http://www.newegg.com/Product/Product.aspx?Item=N82E16814127943 http://www.newegg.com/Product/Product.aspx?Item=N82E16814127945 http://www.newegg.com/Product/Product.aspx?Item=N82E16814127947 http://www.newegg.com/Product/Product.aspx?Item=N82E16814487248 http://www.newegg.com/Product/Product.aspx?Item=N82E16814487245 http://www.newegg.com/Product/Product.aspx?Item=N82E16814487245 http://www.newegg.com/Product/Product.aspx?Item=N82E16814487244 http://www.newegg.com/Product/Product.aspx?Item=N82E16814125869 http://www.newegg.com/Product/Product.aspx?Item=N82E16814125873 http://www.newegg.com/Product/Product.aspx?Item=N82E16814487249 http://www.newegg.com/Product/Product.aspx?Item=N82E16814125871 http://www.newegg.com/Product/Product.aspx?Item=N82E16814127951 http://www.newegg.com/Product/Product.aspx?Item=N82E16814127955)
STOCK="product_instock:['0']"
while true
MAIL=false
do
  for i in "${URL[@]}"
  do
    if [ `curl -s ${i} | grep -F -c "product_instock:['0']"` == 0 ]; then
      echo "${i}" | mail -s "card in stock" ${MYEMAIL}
      MAIL=TRUE
    fi
  done
  if [ $MAIL == TRUE ]; then
    sleep 300
  else
    sleep 10
  fi
done
